eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


server:
  port: 8002
spring:
  application:
    name: points-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata-points?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    password: 12345678
    username: root

logging:
  level:
    io:
      seata: DEBUG